create_clock -period 10.000 -waveform {0.000 5.000} [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN E3 [get_ports clk]

set_property IOSTANDARD LVCMOS33 [get_ports {key[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports adc_clk_out]
set_property IOSTANDARD LVCMOS33 [get_ports continuous_switch]
set_property IOSTANDARD LVCMOS33 [get_ports convst1]
set_property IOSTANDARD LVCMOS33 [get_ports convst2]
set_property IOSTANDARD LVCMOS33 [get_ports mode_switch]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports sda1]
set_property IOSTANDARD LVCMOS33 [get_ports sda2]
set_property PACKAGE_PIN A11 [get_ports sda1]
set_property PACKAGE_PIN A18 [get_ports sda2]
set_property PACKAGE_PIN K16 [get_ports adc_clk_out]
set_property PACKAGE_PIN A8 [get_ports mode_switch]
set_property PACKAGE_PIN C11 [get_ports continuous_switch]

set_property PACKAGE_PIN E15 [get_ports {key[0]}]
set_property PACKAGE_PIN E16 [get_ports {key[1]}]
set_property PACKAGE_PIN D15 [get_ports {key[2]}]
set_property PACKAGE_PIN C15 [get_ports {key[3]}]
set_property PACKAGE_PIN J17 [get_ports {key[4]}]
set_property PACKAGE_PIN J18 [get_ports {key[5]}]
set_property PACKAGE_PIN K15 [get_ports {key[6]}]
set_property PACKAGE_PIN J15 [get_ports {key[7]}]
set_property PACKAGE_PIN U12 [get_ports {key[8]}]
set_property PACKAGE_PIN V12 [get_ports {key[9]}]
set_property PACKAGE_PIN V10 [get_ports {key[10]}]
set_property PACKAGE_PIN V11 [get_ports {key[11]}]
set_property PACKAGE_PIN U14 [get_ports {key[12]}]
set_property PACKAGE_PIN V14 [get_ports {key[13]}]
set_property PACKAGE_PIN T13 [get_ports {key[14]}]
set_property PACKAGE_PIN U13 [get_ports {key[15]}]
set_property PACKAGE_PIN D4 [get_ports {key[16]}]
set_property PACKAGE_PIN D3 [get_ports {key[17]}]
set_property PACKAGE_PIN F4 [get_ports {key[18]}]
set_property PACKAGE_PIN F3 [get_ports {key[19]}]

set_property PULLTYPE PULLUP [get_ports adc_on]
set_property PULLTYPE PULLUP [get_ports sda1]
set_property PULLTYPE PULLUP [get_ports sda2]

set_property PACKAGE_PIN E2 [get_ports {key[20]}]
set_property PACKAGE_PIN D2 [get_ports {key[21]}]
set_property PACKAGE_PIN H2 [get_ports {key[22]}]
set_property PACKAGE_PIN G2 [get_ports {key[23]}]

set_property PACKAGE_PIN C2 [get_ports reset]

set_property IOSTANDARD LVCMOS33 [get_ports busy1]
set_property IOSTANDARD LVCMOS33 [get_ports busy2]
set_property PACKAGE_PIN B11 [get_ports busy1]
set_property PACKAGE_PIN G13 [get_ports convst1]
set_property PACKAGE_PIN B18 [get_ports busy2]
set_property PACKAGE_PIN D13 [get_ports convst2]


set_property IOSTANDARD LVCMOS33 [get_ports adc_clk]
set_property PACKAGE_PIN E7 [get_ports adc_clk]

set_property IOSTANDARD LVCMOS33 [get_ports adc_on]
set_property PACKAGE_PIN D12 [get_ports adc_on]
